### ! books
POST http://localhost:5000/api/books
Content-Type: application/json

{
    "title": "DSA for life <3 1>",
    "author": "67405cacb632cceae59213d7",
    "genres": ["Technology", "Programming"],
    "description": "A comprehensive guide to microservice architecture.",
    "publish_year": 2024
}
### books
GET http://localhost:5000/api/books
### get book by id
@book_id = 67405659dfe3478b3de8f36c
@book_id2 = 67498961c8d0ce78b4c95647
###
GET http://localhost:5000/api/books/book/{{book_id2}}

###! library
### create
POST http://localhost:5000/api/books/libraries
Content-Type: application/json

{
  "user": "user123",
  "name": "My Favorite Books",
  "book_ids": ["67405659dfe3478b3de8f36c", "67405c086cbc1caa79d149d3"]
}

### get all
GET http://localhost:5000/api/books/libraries
### var
@library_id = 674b7c523a082c29fbd051f9
@user_id = user123
### get by id 
GET http://localhost:5000/api/books/libraries/{{library_id}}
### get by user id 
GET http://localhost:5000/api/books/libraries/user/{{user_id}}

### ! history
### create 
POST http://localhost:5000/api/books/histories
Content-Type: application/json

{
  "user": "user123456",
  "chapterId": "674354680dc06ae1b52310a3",
  "voice": "Voice123456"
}
### GET all
###
GET http://localhost:5000/api/books/histories
###
@history_id = 674f37370e1024da7266bac2
@user_id = user123
###
GET http://localhost:5000/api/books/histories/{{history_id}}
###
GET http://localhost:5000/api/books/histories/user/{{user_id}}


###! ratings
### rating
POST http://localhost:5000/api/books/rating
Content-Type: application/json

{
  "id": "64fe0b23a1d4b637c7654321",
  "user": "user123",
  "book_id": "67405659dfe3478b3de8f36c",
  "rating": 3,
  "review": "Great book!"
}

###! AUTHORS
### authors
POST http://localhost:5000/api/books/authors
Content-Type: application/json

{
  "user": "user_001",
  "pen_name": "Khoi Nguyen",
  "name": "Jonathan Doe",
  "description": "An experienced author specializing in science fiction."
}

### get all authors 
GET http://localhost:5000/api/books/authors
###
@author_id = 67405cacb632cceae59213d7
### get author by id
GET http://localhost:5000/api/books/authors/{{author_id}}

### mediafiles
POST http://localhost:5000/api/books/mediafiles
Content-Type: application/json

{
  "file_collection": "book_covers_2_nhe",
  "file_url": "https://example.com/media/book_cover.jpg",
  "file_type": "image/jpeg",
  "file_size": 1024
}

###upload
POST http://localhost:5000/api/books/mediafiles/upload
Content-Type: application/json

{
  "file_name": "example.jpg",
  "file_content": "BASE64_ENCODED_FILE_CONTENT",
  "file_type": "image/jpeg"
}
###! Chapter
### chapters
POST http://localhost:5000/api/books/chapters
Content-Type: application/json

{
  "name": "Chapter 5",
  "book_id": "67405659dfe3478b3de8f36c"
}

### "text_file_id": "64fdfc1e839be305c43d6a2f",
### "audio_file_ids": ["64fdfc4b839be305c43d6a3a"]

### get all
GET http://localhost:5000/api/books/chapters
###
@book_id = 67405659dfe3478b3de8f36c
### get chapters by book id
GET http://localhost:5000/api/books/chapters/{{book_id}}
###
@chapter_id = 674354680dc06ae1b52310a3
@chapter_id2 = 674354680dc06ae1b52310a3
###
GET http://localhost:5000/api/books/chapters/chapter/{{chapter_id2}}
###
PUT http://localhost:5000/api/books/chapters/{{chapter_id}}
Content-Type: application/json

{
  "name": "Updated Chapter Name",
  "text_file_id": "64fdfc1e839be305c43d6a2f",
  "audio_file_ids": ["64fdfc4b839be305c43d6a3a"]
}

# ! comments
### comments
POST http://localhost:5000/api/books/chapters/{{chapter_id}}/comments
Content-Type: application/json

{
  "user": "useroneidinuserservice im nguyen",
  "comment": "I love this chapter <3 fall i luv with u> guys"
}
