### books
POST http://localhost:5000/api/books
Content-Type: application/json

{
    "title": "CPP in one day",
    "author": "645c9fbd9c5e7c0015c1a4d9",
    "genres": ["Technology", "Programming"],
    "description": "A comprehensive guide to microservice architecture.",
    "publish_year": 2024
}

### authors
POST http://localhost:5000/api/books/authors
Content-Type: application/json

{
  "user": "user_001",
  "pen_name": "Khoi Nguyen",
  "name": "Jonathan Doe",
  "description": "An experienced author specializing in science fiction."
}

### mediafiles
POST http://localhost:5000/api/books/mediafiles
Content-Type: application/json

{
  "file_collection": "book_covers_2_nhe",
  "file_url": "https://example.com/media/book_cover.jpg",
  "file_type": "image/jpeg",
  "file_size": 1024
}

###upload
POST http://localhost:5000/api/books/mediafiles/upload
Content-Type: application/json

{
  "file_name": "example.jpg",
  "file_content": "BASE64_ENCODED_FILE_CONTENT",
  "file_type": "image/jpeg"
}
### chapters
POST http://localhost:5000/api/books/chapters
Content-Type: application/json

{
  "name": "Chapter 3",
  "book_id": "64fdfb2c839be305c43d6a1e"
}

### "text_file_id": "64fdfc1e839be305c43d6a2f",
### "audio_file_ids": ["64fdfc4b839be305c43d6a3a"]

### get all
GET http://localhost:5000/api/books/chapters
###
@book_id = 67405659dfe3478b3de8f36c
### get chapters by book id
GET http://localhost:5000/api/books/chapters/{{book_id}}
###
@chapter_id = 674354680dc06ae1b52310a3
###
GET http://localhost:5000/api/books/chapters/chapter/{{chapter_id}}
###
PUT http://localhost:5000/api/books/chapters/{{chapter_id}}
Content-Type: application/json

{
  "name": "Updated Chapter Name",
  "text_file_id": "64fdfc1e839be305c43d6a2f",
  "audio_file_ids": ["64fdfc4b839be305c43d6a3a"]
}

### comments
POST http://localhost:5000/api/books/chapters/{{chapter_id}}/comments
Content-Type: application/json

{
  "user": "useroneidinuserservice",
  "comment": "I love this chapter <3 fall i luv with u>"
}