POST http://localhost:5000/api/voices
Content-Type: application/json

{
  "name": "Sample Voice",
  "typeId": "64fe5678abcd1234ef907890",
  "languageId": "64fe1234abcd5678ef901234",
  "deviceProfileId": "64fe3456abcd7890ef123456",
  "gender": "Male",
  "age": 30,
  "fileName": "sample.mp3",
  "fileContent": "BASE64_ENCODED_STRING_HERE",
  "fileType": "audio/mpeg"
}

### get all
GET http://localhost:5000/api/voices
### 
@voice_id = 67506330d84107073dcdeaea
### get by id 
GET http://localhost:5000/api/voices/{{voice_id}}
### 

### 
POST http://localhost:5001/api/convert
Content-Type: application/json

{
  "text": "Hello, how are you?, i love you",
  "languageCode": "vi-VN",
  "voiceName": "vi-VN-Neural2-D",
  "gender": "MALE",
  "outputFile": "output3.mp3"
}

#! too long to try again
# {
#   "text": "Nhà em ở nơi cao nhất của làng, vì vậy, chỉ cần ra trước sân có thể nhìn bao quát xuống cả vùng quê yên ả. Trước đôi mắt của em, là cả một vùng xanh bao la bát ngát. Đó là sắc xanh của những thửa lúa đương thì con gái tươi non mơn mởn. Đó là sắc xanh của những bãi cỏ, những luống rau, những chùm cây ăn quả xum xuê, nhờ bàn tay người nông dân chăm chỉ. Đó còn là sắc xanh của bầu trời cao ở ngay trên đỉnh đầu, nơi mà những ngày đầu đông tưởng như có thể vươn tay lên chạm tới. Vẻ đẹp mộc mạc mà giản dị ấy, khiến em luôn tha thiết yêu thương quê hương mình. Chắc chắn rằng! Dù sau này có đi đến xứ sở nào, thì quê hương vẫn mãi là nơi tuyệt vời nhất trong trái tim của em.  ",
#   "languageCode": "vi-VN",
#   "voiceName": "vi-VN-Standard-C",
#   "gender": "MALE",
#   "outputFile": "output5.mp3"
# }





